// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportBook(arg1:string):Promise<string>;

export function OpenEpubDialog():Promise<string>;

export function SetupDataDirectory():Promise<void>;
