// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportBook(arg1) {
  return window['go']['main']['App']['ImportBook'](arg1);
}

export function OpenEpubDialog() {
  return window['go']['main']['App']['OpenEpubDialog']();
}

export function SetupDataDirectory() {
  return window['go']['main']['App']['SetupDataDirectory']();
}
